### ISSUE TITLE
preflight CORS 오류

### ISSUE THREAD

**Issue by sky21kr** [sky21kr/teampl#2]
https://www.popit.kr/cors-preflight-%EC%9D%B8%EC%A6%9D-%EC%B2%98%EB%A6%AC-%EA%B4%80%EB%A0%A8-%EC%82%BD%EC%A7%88/

https://velog.io/@ojwman/spring-boot-cors-header-preflight

preflight 관련 cors 에러가 발생하는 것 같습니다. 해당 링크 참고하여 확인해주시면 감사하겠습니다. 해당 오류는 로그인 후 팀만들기에서 발생하고 있습니다.

![image](https://user-images.githubusercontent.com/19388573/124002816-2bdaf080-da11-11eb-9d29-2b82e4675c81.png)

**Comment by binimini** [comment]
preflight 시 Options request에서도 헤더에서 인증을 위한 userId 값을 요구해 500 Internal server error가 나는 문제였습니다.
Options request인 경우 헤더에서 userId 값을 요구하지 않도록 처리해 해결했습니다.
