### ISSUE TITLE
/team-make API 호출 시 userId

### ISSUE THREAD

**Issue by sky21kr** [sky21kr/teampl#3]
admin / 1111

계정으로 로그인하여 userId 583을 받아 team-make 헤더에 요청하니 다음과 같은 에러가 발생합니다. 확인해주시면 감사하겠습니다.

![image](https://user-images.githubusercontent.com/19388573/124163025-209fc780-dada-11eb-8808-23ae5ef2688e.png)
![image](https://user-images.githubusercontent.com/19388573/124163055-28f80280-dada-11eb-9f63-861209e47d5f.png)
![image](https://user-images.githubusercontent.com/19388573/124163153-40cf8680-dada-11eb-8bcc-2814c3813d04.png)

**Comment by binimini** [comment]
승민님 owner에 팀 만드는 user id 값 한번 더 넣어주셔야 합니다. 
팀 소유자 정보가 0으로 되어있어서 예외 발생하는 걸꺼에요. 확인 부탁드려요!

**Comment by sky21kr** [comment]
확인하였습니다.
