### ISSUE TITLE
[commnet] create API 입력 파라미터 수정 요청

### ISSUE THREAD

**Issue by sky21kr** [sky21kr/teampl#4]
comment 생성시 comment id랑 datetime은 파라미터 입력으로 받는 것이 아닌 코멘트 생성시 자동으로 생성되게 해주시면 감사하겠습니다.

![image](https://user-images.githubusercontent.com/19388573/124548099-3578b400-de68-11eb-8dbf-e45d87b6a0c9.png)

**Comment by heyazoo1007** [comment]
commentid는 refCommentId로 수정했고, datetime 필드 삭제했습니다. CommentService 클래스, createComment 메서드에 datetime  자동 생성되게 했습니다.

**Comment by heyazoo1007** [comment]
배포 부탁드리겠습니다!

**Comment by penguin234** [comment]
backend 브랜치에 수정사항 머지하고
배포했습니다.

**Comment by sky21kr** [comment]
comment쪽 파라미터가 나오지 않습니다. 배포 적용이 안된 것인지 확인해주시면 감사하겠습니다.

![image](https://user-images.githubusercontent.com/19388573/125499083-84b5d7cb-1039-4192-9f52-244dfb09a935.png)
