### ISSUE TITLE
[comment] delete API 관련 수정 사항

### ISSUE THREAD

**Issue by sky21kr** [sky21kr/teampl#5]
comment delete API를 get 방식이 아닌 delete 방식으로, 입력 파라미터를 comment id만 받게 수정해주시면 감사하겠습니다.

![image](https://user-images.githubusercontent.com/19388573/124548516-ca7bad00-de68-11eb-8f48-9b112dcc256d.png)

**Comment by heyazoo1007** [comment]
@getmapping을 @deletemapping으로 수정했고, 파라미터 comment_id만 있게 수정했습니다.
